config/routes.rb
Discountwheel::Application.routes.draw do

  get  '/wheel/terms',          to: 'wheel#terms'
  get  '/wheel/spin',           to: 'wheel#spin'
  get  '/wheel/already_played', to: 'wheel#already_played'
  get  '/callback',             to: 'sessions#index'

  get  '/wheel',                to: 'wheel#index'
  get  '/terms',                to: 'wheel#terms'
  post '/',                     to: 'sessions#create'

  get '/spins/reset',          to: 'spins#reset'
  resources :spins, only: [:index, :update, :destroy]

end

app/models/discount_wheel_spin.rb
class DiscountWheelSpin < ActiveRecord::Base
  belongs_to :user

  def give!
    self.given = true
    self.save!
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :discount_wheel_spins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  before_filter :set_p3p
  helper_method :signed_request_data

  def signed_request_data
    @_signed_request_data = JSON.parse(base64_url_decode(params[:signed_request].split('.', 2)[1])) if params[:signed_request]
  end

  def base64_url_decode(str)
    str += '=' * (4 - str.length.modulo(4))
    Base64.decode64(str.tr('-_','+/'))
  end

  def user_likes_page?(user, page_id)
    facebook_likes_for(user).include?(page_id.to_s)    
  end

  def facebook_data_for(user)
    p = Proc.new do
      path = "/#{user.fb_id}?oauth_token=#{user.oauth_token}"
      http = Net::HTTP.new('graph.facebook.com', 443)
      http.use_ssl = true
      res = http.get(path, nil)

      JSON.parse(res.body)
    end

    @_user_graph_data ||= p.call
  end

  def facebook_likes_for(user)
    logger.debug "USER: #{user}"
    path = "/#{user.fb_id}?fields=likes&oauth_token=#{user.oauth_token}"
    http = Net::HTTP.new('graph.facebook.com', 443)
    http.use_ssl = true
    res = http.get(path, nil)

    data = JSON.parse(res.body)

    data['likes']['data'].map { |p| p['id'] }
  end

  def current_user
    @_current_user ||= session[:current_user_id] && User.where(fb_id: session[:current_user_id])
  end

  def logged_in?
    current_user.present?
  end

  def init_instance_variables
    @app_id     = '371914089608290'
    @page_name  = 'mania.pernik'
    @page_id    = '372485692804942'

    @callback_url        = URI.escape("https://discountwheel.herokuapp.com/callback")
    @page_tab_canvas_url = "https://www.facebook.com/pages/#{@page_name}/#{@page_id}?id=#{@page_id}&v=app_#{@app_id}"
    @scope               = 'email,user_likes'

    @auth_url = "https://www.facebook.com/dialog/oauth?client_id=#{@app_id}&redirect_uri=#{@callback_url}&scope=#{@scope}"
  end

  private

  def set_p3p
    headers['P3P'] = 'CP="IDC DSP COR CURa ADMa OUR IND PHY ONL COM STA"'
  end

end

app/controllers/sessions_controller.rb
require "net/http"

class SessionsController < ApplicationController

  before_filter :init_instance_variables

  def index
  end

  def create
    unless signed_request_data.nil? || signed_request_data['user_id'].nil?

      user = User.where(fb_id: signed_request_data['user_id']).first_or_create

      # Update user data
      user.oauth_token            = signed_request_data['oauth_token']
      user.oauth_token_issued_at  = DateTime.strptime(signed_request_data['issued_at'].to_s,'%s')
      user.oauth_token_expires_at = DateTime.strptime(signed_request_data['expires'].to_s,'%s')

      user.name    = facebook_data_for(user)['first_name']
      user.surname = facebook_data_for(user)['last_name']
      user.email   = facebook_data_for(user)['email']
      user.gender  = facebook_data_for(user)['gender']

      user.save

      # Create session
      session[:current_user_id] = user.fb_id

      redirect_to wheel_path
    end
  end

end

app/controllers/spins_controller.rb
class SpinsController < ApplicationController

  layout 'admin'

  def index
    if params[:code].present?
      @pending_winnings = [DiscountWheelSpin.find(params[:code])] rescue []
      @no_results_message = 'Няма печалба с такъв код.'
    else
      @pending_winnings = DiscountWheelSpin.where(given: false)
      @no_results_message = 'Няма чакащи награждавания.'
    end

    @given_winnings = DiscountWheelSpin.where(given: true)
  end

  def update
    spin = DiscountWheelSpin.find(params[:id])
    spin.give!

    redirect_to spins_path
  end

  def reset
    DiscountWheelSpin.destroy_all
    redirect_to spins_path
  end

  def destroy
    @spin = DiscountWheelSpin.find(params[:id])
    @spin.destroy
    redirect_to spins_path
  end
end

app/controllers/wheel_controller.rb
class WheelController < ApplicationController

  helper_method :prize_for, :text_for, :code_for

  before_filter :init_instance_variables

  before_filter do
    logger.debug "CURRENT_USER: #{current_user}"
    logger.debug "PAGE_ID: #{@page_id}"
    @likes_page = user_likes_page?(current_user, @page_id)
  end

  before_filter :verify_allowed_to_spin, except: [:already_played]

  def terms
  end

  def index
  end

  def spin
    @angle = 2 * 360 + ((rand(360) / 15).floor * 15)
    @prize = prize_for(@angle)
    @spin  = DiscountWheelSpin.new({ prize: @prize })

    current_user.discount_wheel_spins << @spin
    current_user.save

    respond_to do |format|
      format.js
    end
  end

  def already_played
  end

  private

  def verify_allowed_to_spin
    redirect_to wheel_already_played_path if current_user.discount_wheel_spins.any?
  end

  def prize_for(angle)
    wheel_sectors = [ 20, 15, 25, 30, 20, 15, 100, 15, 20, 30, 25, 15, 20, 15, 20, 25, 20, 15, 25, 15, 20, 25, 20, 15 ]

    wheel_sectors[((angle - 720) / 15).round]
  end

  def text_for(prize)
    if(prize == 100)
      'безплатна дреха'
    else
      "#{prize}% отстъпка"
    end
  end

  def code_for(spin)
    "2008#{spin.id}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mania Administration</title>
  <%= stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "admin", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller].dasherize %> <%= params[:action].dasherize %>">

  <div class="container">
    <div class="row logo">
      <div class="col-xs-12">
        <%= image_tag 'logo.png' %>
      </div>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mania</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller].dasherize %> <%= params[:action].dasherize %>">

  <div id="wrapper">
    <%= yield %>
  </div>

</body>
</html>

app/views/spins/index.html.erb
<div class="row">
  <%= form_tag spins_path, method: :get, class: 'form-inline', role: 'form' do %>
    <div class="code-input col-xs-8 form-group">
      <span class="code-prefix">2008</span>
      <%= number_field_tag :code, nil, placeholder: 'КОД НА НАГРАДА', class: 'form-control' %>
    </div>
    <div class="col-xs-4">
      <%= button_tag 'Търси награда', class: 'btn btn-default btn-primary btn-block' %>
    </div>
  <% end %>
</div>

</br>
</br>

<h1>Нераздадени печалби</h1>

<div class="row">
  <div class="col-xs-12">
    <table class="pending table table-hover">
      <thead>
        <tr>
          <th>Код</th>
          <th>Име</th>
          <th>Фамилия</th>
          <th>Имейл</th>
          <th>Пол</th>
          <th>Награда</th>
          <th>Играно на</th>
          <th>Даване на награда?</th>
          <th>Изтриване?</th>
        </tr>
      </thead>
      <tbody>
        <% @pending_winnings.each do |pending_winning| %>
          <tr>
            <td style="font-size:16px;font-weight:bold;"><%= "2008#{pending_winning.id}" %></td>
            <td><%= pending_winning.user.name %></td>
            <td><%= pending_winning.user.surname %></td>
            <td><%= pending_winning.user.email %></td>
            <td><%= pending_winning.user.gender %></td>
            <td><%= pending_winning.prize %></td>
            <td>преди <%= distance_of_time_in_words(pending_winning.created_at, Time.now) %></td>
            <td><%= button_to('Дай', spin_path(pending_winning), confirm: 'Сигурни ли сте?', method: :put, class: 'btn btn-primary') %></td>
            <td><%= button_to('Изтрий', spin_path(pending_winning), confirm: 'Сигурни ли сте?', method: :delete, class: 'btn btn-danger') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    </br>

    <% unless @pending_winnings.any? %>
      <div class="no-results">
        <%= @no_results_message %>
      </div>
    <% end %>
  </div>
</div>

<h1>Раздадени награди</h1>

<div class="row">
  <div class="col-xs-12">
    <table class="given table table-hover">
      <thead>
        <tr>
          <th>Код</th>
          <th>Име</th>
          <th>Фамилия</th>
          <th>Имейл</th>
          <th>Пол</th>
          <th>Награда</th>
          <th>Играно на</th>
          <th>Получено на</th>
        </tr>
      </thead>
      <tbody>
        <% @given_winnings.each do |given_winning| %>
          <tr>
            <td style="font-size:16px;font-weight:bold;"><%= "2008#{given_winning.id}" %></td>
            <td><%= given_winning.user.name %></td>
            <td><%= given_winning.user.surname %></td>
            <td><%= given_winning.user.email %></td>
            <td><%= given_winning.user.gender %></td>
            <td><%= given_winning.prize %></td>
            <td>преди <%= distance_of_time_in_words(given_winning.created_at, Time.now) %></td>
            <td>преди <%= distance_of_time_in_words(given_winning.updated_at, Time.now) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    </br>

    <% unless @given_winnings.any? %>
      <div class="no-results">
        Няма раздадени награди.
      </div>
    <% end %>
  </div>
</div>

app/views/wheel/_prize_information.html.erb
<div id="prize_information">
  <h1>Честито!</h1>
  <p>
    Вие спечелихте<br/>
    <strong><%= prize %></strong><br/>
    в магазин Мания - Перник.<br/>
    Заповядайте на място на адрес<br/>
    <u>площад "Кракра" №17</u>,<br/>
    за да я получите.
  </p>

  <div id="discount_code">
    <div class="sup-info">Код на остъпката:</div>
    <span><%= code %></span>
    <div class="sub-info">кажете го на касата, за да получите наградата си</div>
  </div>
</div>

app/views/wheel/already_played.html.erb
<h1>Вие вече сте участвали в играта.</h1>

<%= image_tag 'logo.png', id: 'logo' %>

app/views/wheel/index.html.erb
<% if @likes_page %>
  <%= link_to '', wheel_spin_path, remote: true, id: 'spin_button'%>
  <%= link_to 'Правила за участие*', terms_path, id: 'terms_button'%>
  <span id="terms_footnote">
    *Моля, прочетете правилата на играта преди да участвате
  </span>
<% else %>
  <%= image_tag 'like_to_play.png', id: 'like_to_play' %>
<% end %>

<div id="wheel_container">
  <%= image_tag 'arrow.png', id: 'win_sector' %>
  <%= image_tag 'shield.png', id: 'wheel_center' %>
</div>

<script type="text/javascript">
  var wheel;

  $(document).ready(function(){
    wheel = new Wheel();
  });

</script>

<%= image_tag 'logo.png', id: 'logo' %>

app/views/wheel/spin.js.erb
$('#spin_button').hide();
$('#terms_button').hide();
$('#terms_footnote').hide();

wheel.spin(-10, 500, function(){

  wheel.spin(<%= @angle %>, 9000, function(){
    $('#wheel_container').animate({
        left: "-=260",
      }, 1000, function() {
        $('#wrapper').append('<%= j render partial: "prize_information", locals: { prize: text_for(@prize), code: code_for(@spin) } %>');
        $('#prize_information').hide().fadeIn(500);
      }
    );

  });

});

app/views/wheel/terms.html.erb
<h1>Правила за участие</h1>

<%= link_to 'Назад', wheel_path, id: 'back_button' %>

<p>"Колелото на късмета" е Фейсбук игра, която се провежда във фен страницата на магазин "Мания" град Перник. Участниците в нея имат шанса да спечелят отстъпки от 15 до 30 процента или безплатна дреха. Условия и параметри на играта:</p>

<ul>
	<li>Намалението не важи за предпремиери.</li>
	<li>Играта ще бъде активна до 28.02.2014г.</li>
	<li>Печалбите от играта ще могат да бъдат получени до 31.03.2014г.</li>
	<li>Печалбите важат за магазин "Мания" град Перник.</li>
	<li>Всеки потребител може да участва еднократно в играта.</li>
	<li>Намалението важи само за дрехи.</li>
	<li>Намалението не се комбинира с други промоции или отстъпки.</li>
	<li>За да получи наградата си, всеки потребител трябва да предостави кодът, който е получил след участието си на касата в магазина.</li>
</ul>